In [2]:
import torch

In [3]:
x=torch.rand(3, requires_grad=True)
x

tensor([0.7720, 0.9854, 0.3702], requires_grad=True)

In [4]:
y=x+2
y

tensor([2.7720, 2.9854, 2.3702], grad_fn=<AddBackward0>)

In [5]:
z=y*y*2
z

tensor([15.3680, 17.8257, 11.2356], grad_fn=<MulBackward0>)

In [6]:
z=z.mean()
print(z)

tensor(14.8098, grad_fn=<MeanBackward0>)


In [7]:
z.backward()

In [8]:
x

tensor([0.7720, 0.9854, 0.3702], requires_grad=True)

In [9]:
x.grad

tensor([3.6960, 3.9806, 3.1603])

In [10]:
x=torch.rand(3, requires_grad=False)
x

tensor([0.5060, 0.3667, 0.4414])

In [11]:
y=x+2
y

tensor([2.5060, 2.3667, 2.4414])

In [12]:
z=y*y*2
z

tensor([12.5603, 11.2023, 11.9207])

In [13]:
z.mean()

tensor(11.8944)

In [14]:
z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [15]:
x=torch.rand(3, requires_grad=True)
x

tensor([0.3323, 0.5613, 0.5543], requires_grad=True)

In [22]:
y=x*x*2
y

tensor([0.2208, 0.6302, 0.6146], grad_fn=<MulBackward0>)

In [17]:
#y=y.mean()
#print(y)

tensor(0.4885, grad_fn=<MeanBackward0>)


In [18]:
y.backward()

In [19]:
y.grad

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\torch\_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:475.)
  return self._grad


In [20]:
x.grad

tensor([0.4430, 0.7484, 0.7391])

In [21]:
y

tensor(0.4885, grad_fn=<MeanBackward0>)

In [23]:
y

tensor([0.2208, 0.6302, 0.6146], grad_fn=<MulBackward0>)

In [24]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [25]:
# Now we have create a vector same size
v=torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([0.5759, 2.9937, 0.7413])


In [26]:
#x.requires_grad_(false)
#x.detach
#eith torch.no_grad()
x=torch.randn(3, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([-1.5360,  1.3598, -0.0130], requires_grad=True)
tensor([-1.5360,  1.3598, -0.0130])


In [27]:
x=torch.randn(3, requires_grad=True)
print(x)
y=x.detach()
print(y)

tensor([ 1.0509, -1.1522,  0.0239], requires_grad=True)
tensor([ 1.0509, -1.1522,  0.0239])


In [31]:
x=torch.randn(3, requires_grad=True)
print(x)
with torch.no_grad():
    y=x+2
    print(y)

tensor([2.7539, 1.2529, 1.0697], requires_grad=True)
tensor([4.7539, 3.2529, 3.0697])


In [34]:
weights=torch.ones(4, requires_grad=True)
for i in range(1):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])


In [35]:
weights=torch.ones(4, requires_grad=True)
for i in range(2):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [36]:
weights=torch.ones(4, requires_grad=True)
for i in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [37]:
weights=torch.ones(4, requires_grad=True)
for i in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [38]:
weights=torch.rand(4, requires_grad=True)
optimizer=torch.optim.SGD(weights, lr=0.001)
optimizer.step()
print(weights.grad)
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor