In [1]:
import torch

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x=torch.rand(3, requires_grad=True)
x

tensor([0.4311, 0.3266, 0.3062], requires_grad=True)

In [3]:
y=x+2
y

tensor([2.4311, 2.3266, 2.3062], grad_fn=<AddBackward0>)

In [4]:
z=y*y*2
print(z)

tensor([11.8207, 10.8258, 10.6374], grad_fn=<MulBackward0>)


In [5]:
z=z.mean()
print(z)

tensor(11.0946, grad_fn=<MeanBackward0>)


In [6]:
z.backward() #dz/dx

In [7]:
x.grad

tensor([3.2415, 3.1021, 3.0750])

In [8]:
x=torch.rand(3, requires_grad=False)
x

tensor([0.4905, 0.0932, 0.4209])

In [9]:
y=x+2
y

tensor([2.4905, 2.0932, 2.4209])

In [10]:
z=y*y*2
z

tensor([12.4049,  8.7627, 11.7216])

In [14]:
z.mean()


tensor(10.9631)

In [15]:
z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [16]:
x=torch.rand(3, requires_grad=True)

In [17]:
x

tensor([0.6961, 0.6220, 0.6576], requires_grad=True)

In [18]:
y=x+2
y

tensor([2.6961, 2.6220, 2.6576], grad_fn=<AddBackward0>)

In [19]:
z=y*y*2
z

tensor([14.5381, 13.7497, 14.1262], grad_fn=<MulBackward0>)

In [20]:
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [21]:
v=torch.tensor([0.1,1.0,0.001], dtype=torch.float32)

In [22]:
v

tensor([0.1000, 1.0000, 0.0010])

In [23]:
z.backward(v)

In [24]:
print(x.grad)

tensor([ 1.0784, 10.4880,  0.0106])


In [25]:
#x.requires_grad_(false)
#x.detach
#with torch.no_grad():


In [31]:
x=torch.rand(3, requires_grad=True)
x

tensor([0.4817, 0.2082, 0.7457], requires_grad=True)

In [27]:
#x.requires_grad_(False)
#print(x)

tensor([0.2098, 0.1115, 0.7919])


In [32]:
y=x.detach()# this will create a new vector
print(y)

tensor([0.4817, 0.2082, 0.7457])


In [34]:
#with torch.no_grad():
y=x+2
print(y)

tensor([2.4817, 2.2082, 2.7457], grad_fn=<AddBackward0>)


In [38]:
weights=torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [40]:
optimizer=torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.grad.zero_()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor