In [1]:
import torch

In [3]:
x=torch.rand(3, requires_grad=True)
print(x)

tensor([0.9536, 0.2358, 0.0843], requires_grad=True)


In [4]:
y=x+2
"""
backpropagation
then calculate the gradients
First we do a forward pass so we apply the add operation here and we calculate the output y. Since we specified we requires a gradient
PyTorch will then automatically create and store a function and this function is used in the backpropagation and to get the gradient
So here y has an attribute grad_fm and this will point to a gradient function and its called backword and with this function we can then calculate
the gradient so called backword pass.. So this will calculate the gradient of y with respect to x
"""
print(y)

tensor([2.9536, 2.2358, 2.0843], grad_fn=<AddBackward0>)


In [5]:
z=y*y*2
print(z)

tensor([17.4473,  9.9979,  8.6889], grad_fn=<MulBackward0>)


In [6]:
z=z.mean()
print(z)

tensor(12.0447, grad_fn=<MeanBackward0>)


In [7]:
z.backward()
x.grad

tensor([3.9381, 2.9811, 2.7791])

In [8]:
x=torch.rand(3, requires_grad=False)
x

tensor([0.3094, 0.2669, 0.8822])

In [9]:
y=x+2
print(y)

tensor([2.3094, 2.2669, 2.8822])


In [10]:
z=y*y*2
print(z)

tensor([10.6665, 10.2773, 16.6139])


In [11]:
z=z.mean()
print(z)

tensor(12.5192)


In [12]:
z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [19]:
x=torch.rand(3, requires_grad=True)
print(x)

tensor([0.0484, 0.1503, 0.7245], requires_grad=True)


In [20]:
y=x+2
print(y)

tensor([2.0484, 2.1503, 2.7245], grad_fn=<AddBackward0>)


In [21]:
z=y*y*2
print(z)

tensor([ 8.3918,  9.2480, 14.8457], grad_fn=<MulBackward0>)


In [16]:
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [22]:
"""
error->grad can be implicitly created only for scalar outputs
in this case we have to give it the gradient argument so we have to create vector of same size lets say
v=torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
we must pass this vector to the gradient function


"""
v=torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([0.8194, 8.6014, 0.0109])


In [27]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():
x=torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.5482, -1.9385,  0.1822], requires_grad=True)


In [24]:
#x.requires_grad_(False)

tensor([-0.4871,  0.3911,  2.1105])

In [25]:
print(x)

tensor([-0.4871,  0.3911,  2.1105])


In [28]:
y=x.detach()
print(y)

tensor([ 0.5482, -1.9385,  0.1822])


In [29]:
with torch.no_grad():
    y=x+2
    print(y)

tensor([2.5482, 0.0615, 2.1822])


In [30]:
y=x+2
print(y)

tensor([2.5482, 0.0615, 2.1822], grad_fn=<AddBackward0>)


In [36]:
weights=torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    print(model_output)
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [37]:
optimizer=torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor