In [1]:
import torch

In [3]:
x=torch.empty(1)
print(x)

tensor([1.4013e-45])


In [4]:
x=torch.empty(2)
print(x)

tensor([9.1477e-41, 0.0000e+00])


In [5]:
x=torch.empty(3)
print(x)

tensor([1.4013e-45, 0.0000e+00, 0.0000e+00])


In [6]:
# making 2D
x=torch.empty(2,3)
print(x)

tensor([[2.9508e+29, 7.5556e+31, 2.2967e-18],
        [1.8590e+34, 7.7767e+31, 1.7181e+19]])


In [7]:
x=torch.empty(2,2,3)
print(x)

tensor([[[0.0000, 2.1250, 0.0000],
         [2.0000, 0.0000, 1.8750]],

        [[0.0000, 1.8750, 0.0000],
         [2.0000, 0.0000, 0.0000]]])


In [8]:
x=torch.empty(2,2,2,3)
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [9]:
x=torch.rand(2,3)
print(x)

tensor([[0.8174, 0.6013, 0.4840],
        [0.6945, 0.1337, 0.2107]])


In [10]:
x=torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [11]:
x=torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [12]:
x.dtype

torch.float32

In [13]:
x=torch.ones(2,2, dtype=torch.float16)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [14]:
print(x.size())

torch.Size([2, 2])


In [15]:
#Create a tensor
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [19]:
# Barics operations
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.5367, 0.6104],
        [0.0471, 0.0791]])
tensor([[0.5737, 0.3253],
        [0.3718, 0.3911]])


In [20]:
z=x+y## Element wise addition
print(z)

tensor([[1.1104, 0.9357],
        [0.4189, 0.4702]])


In [21]:
z=torch.add(x,y)
print(z)

tensor([[1.1104, 0.9357],
        [0.4189, 0.4702]])


In [22]:
# inplace additions
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.1643, 0.9261],
        [0.0145, 0.1633]])
tensor([[0.4783, 0.1858],
        [0.1339, 0.6589]])


In [23]:
y.add_(x)# _this will modify y and add all of the elements of x to y
print(y)

tensor([[0.6426, 1.1119],
        [0.1484, 0.8222]])


In [24]:
z=x-y
print(z)


tensor([[-0.4783, -0.1858],
        [-0.1339, -0.6589]])


In [25]:
z=torch.sub(x,y)
print(z)

tensor([[-0.4783, -0.1858],
        [-0.1339, -0.6589]])


In [26]:
z=x*y
print(z)

tensor([[0.1056, 1.0297],
        [0.0021, 0.1342]])


In [27]:
z=torch.mul(x,y)
print(z)

tensor([[0.1056, 1.0297],
        [0.0021, 0.1342]])


In [28]:
y.mul_(x)
print(y)

tensor([[0.1056, 1.0297],
        [0.0021, 0.1342]])


In [29]:
z=x/y
print(z)

tensor([[1.5562, 0.8994],
        [6.7397, 1.2162]])


In [30]:
z=torch.div(x,y)
print(z)

tensor([[1.5562, 0.8994],
        [6.7397, 1.2162]])


In [31]:
y.div_(x)
print(y)

tensor([[0.6426, 1.1119],
        [0.1484, 0.8222]])


In [32]:
## Tensor sliceing

In [33]:
x=torch.rand(5,3)
print(x)

tensor([[0.4532, 0.9169, 0.9314],
        [0.2114, 0.8274, 0.9822],
        [0.0931, 0.6698, 0.2827],
        [0.7271, 0.9367, 0.8541],
        [0.9076, 0.9069, 0.1981]])


In [34]:
print(x[:,0])

tensor([0.4532, 0.2114, 0.0931, 0.7271, 0.9076])


In [35]:
print(x[:,1])

tensor([0.9169, 0.8274, 0.6698, 0.9367, 0.9069])


In [36]:
print(x[1,:])

tensor([0.2114, 0.8274, 0.9822])


In [37]:
print(x[1,1])

tensor(0.8274)


In [38]:
print(x[1,1].item())

0.8274300694465637


In [39]:
# Reshaping a tensor

In [40]:
x=torch.rand(4,4)
print(x)

tensor([[0.4709, 0.7037, 0.2360, 0.6778],
        [0.1941, 0.7549, 0.9292, 0.4664],
        [0.5024, 0.0700, 0.0850, 0.7393],
        [0.1883, 0.4850, 0.3855, 0.5427]])


In [41]:
y=x.view(16)
print(y)

tensor([0.4709, 0.7037, 0.2360, 0.6778, 0.1941, 0.7549, 0.9292, 0.4664, 0.5024,
        0.0700, 0.0850, 0.7393, 0.1883, 0.4850, 0.3855, 0.5427])


In [42]:
y=x.view(8,2)
print(y)

tensor([[0.4709, 0.7037],
        [0.2360, 0.6778],
        [0.1941, 0.7549],
        [0.9292, 0.4664],
        [0.5024, 0.0700],
        [0.0850, 0.7393],
        [0.1883, 0.4850],
        [0.3855, 0.5427]])


In [43]:
y=x.view(-1,8)
print(y)

tensor([[0.4709, 0.7037, 0.2360, 0.6778, 0.1941, 0.7549, 0.9292, 0.4664],
        [0.5024, 0.0700, 0.0850, 0.7393, 0.1883, 0.4850, 0.3855, 0.5427]])


In [46]:
y=x.view(-1,2)
print(y)

tensor([[0.4709, 0.7037],
        [0.2360, 0.6778],
        [0.1941, 0.7549],
        [0.9292, 0.4664],
        [0.5024, 0.0700],
        [0.0850, 0.7393],
        [0.1883, 0.4850],
        [0.3855, 0.5427]])


# Converting numpy to torch tensor

In [47]:
import numpy as np

In [48]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [49]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [50]:
type(b)

numpy.ndarray

In [51]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [52]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [53]:
print(b)

[2. 2. 2. 2. 2.]


In [54]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [55]:
b=torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [57]:
b.add_(1)
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [58]:
print(a)

[2. 2. 2. 2. 2.]


In [59]:
x=torch.ones(5,requires_grad=True)# 
"""requires_grad=True-> pytorch that it will need to calculate the gradient for this tensor
this means whenever you have a variable in your model
"""
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
