In [1]:
import torch

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
x=torch.tensor([[2,3]])
x

tensor([[2, 3]])

In [8]:
y=torch.tensor([[2,1]])
y

tensor([[2, 1]])

In [9]:
x.shape

torch.Size([1, 2])

In [10]:
y.shape

torch.Size([1, 2])

In [11]:
z=torch.dot(x,y)
z

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [12]:
import numpy as np

In [13]:
a = np.array([1,2])
b = np.array([3,4])

In [14]:
a

array([1, 2])

In [18]:
b[1]

4

In [16]:
len(a)

2

In [19]:
dot=0
for i in range(len(a)):
    dot +=a[i]*b[i]
print(dot)

11


In [20]:
np.dot(a,b)

11

In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.tensor([-1.0, 1.0, 2.0, 3.0])
x
# sofmax
#output = torch.softmax(x, dim=0)
#print(output)

tensor([-1.,  1.,  2.,  3.])

In [22]:
output = torch.softmax(x, dim=0)
print(output)

tensor([0.0120, 0.0889, 0.2418, 0.6572])


In [23]:
sm = nn.Softmax(dim=0)
output = sm(x)
print(output)

tensor([0.0120, 0.0889, 0.2418, 0.6572])


In [24]:
output = torch.sigmoid(x)
print(output)

tensor([0.2689, 0.7311, 0.8808, 0.9526])


In [25]:
s = nn.Sigmoid()
output = s(x)
print(output)

tensor([0.2689, 0.7311, 0.8808, 0.9526])


In [26]:
#tanh
output = torch.tanh(x)
print(output)
t = nn.Tanh()
output = t(x)
print(output)


tensor([-0.7616,  0.7616,  0.9640,  0.9951])
tensor([-0.7616,  0.7616,  0.9640,  0.9951])


In [27]:
# relu
output = torch.relu(x)
print(output)
relu = nn.ReLU()
output = relu(x)
print(output)

tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])


In [28]:
# leaky relu
output = F.leaky_relu(x)
print(output)
lrelu = nn.LeakyReLU()
output = lrelu(x)
print(output)


tensor([-0.0100,  1.0000,  2.0000,  3.0000])
tensor([-0.0100,  1.0000,  2.0000,  3.0000])


In [29]:
# option 1 (create nn modules)
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out