In [1]:
import torch
import numpy as np
import torch.nn as nn


In [3]:
loss=nn.CrossEntropyLoss()
Y=torch.tensor([0])
#nsamples x nclasses=1x3
y_pred_good=torch.tensor([[2.0,1.0,0.1]])
y_pred_bad=torch.tensor([[0.5,2.0,0.3]])
l1=loss(y_pred_good, Y)
l2=loss(y_pred_bad,Y)
print(l1.item())
print(l2.item())

0.4170299470424652
1.840616226196289


In [4]:
_,predictions1=torch.max(y_pred_good,1)
_,predictions2=torch.max(y_pred_bad,1)
print(predictions1)
print(predictions2)

tensor([0])
tensor([1])


In [5]:
# Loss allows pytorch in multiple samples

In [6]:
#3 possible classes
Y=torch.tensor([2,0,1])
#nsamoples x nclasses=3x3
y_pred_good=torch.tensor([[2.0,1.0,2.5],[2.0,1.0,0.1],[2.0,3.0,0.1]])
y_pred_bad=torch.tensor([[0.5,2.0,0.5],[0.1,1.0,2.1],[0.1,3.0,0.1]])
l1=loss(y_pred_good, Y)
l2=loss(y_pred_bad,Y)
print(l1.item())
print(l2.item())
_,predictions1=torch.max(y_pred_good,1)
_,predictions2=torch.max(y_pred_bad,1)
print(predictions1)
print(predictions2)

0.4579531252384186
1.4524747133255005
tensor([2, 0, 1])
tensor([1, 2, 1])
