In [1]:
import torch

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x=torch.randn(3)
print(x)

tensor([ 0.0802, -0.8429,  0.5149])


In [3]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([-0.2274, -0.4201, -0.4967], requires_grad=True)


In [4]:
y=x+2
print(y)

tensor([1.7726, 1.5799, 1.5033], grad_fn=<AddBackward0>)


In [5]:
z=y*y*2
print(z)

tensor([6.2845, 4.9923, 4.5196], grad_fn=<MulBackward0>)


In [6]:
z=z.mean()
print(z)

tensor(5.2655, grad_fn=<MeanBackward0>)


In [7]:
z.backward()
print(x.grad)

tensor([2.3635, 2.1066, 2.0043])


In [25]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([ 1.2358, -0.0862,  1.1620], requires_grad=True)


In [30]:
y=x*2
print(y)

tensor([ 2.4716, -0.1723,  2.3239], grad_fn=<MulBackward0>)


In [31]:
z=y*y*2
print(z)

tensor([12.2177,  0.0594, 10.8014], grad_fn=<MulBackward0>)


In [32]:
#z=z.mean()
#print(z)
v=torch.tensor([0.1, 1.0,0.001], dtype=torch.float32)

In [33]:
z.backward(v)
print(x.grad)

tensor([3.2716, 6.2770, 0.0312])


In [18]:
x.grad

tensor([ 4.4457, -5.3697,  7.5866])

In [34]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.1023, -0.4689,  1.3062], requires_grad=True)


In [36]:
x.requires_grad_(False)
print(x)

tensor([ 0.1023, -0.4689,  1.3062])


In [37]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([ 1.6011, -2.0778,  0.4650], requires_grad=True)


In [38]:
y=x.detach()
print(y)

tensor([ 1.6011, -2.0778,  0.4650])


In [39]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([-1.1637,  0.1483, -0.4919], requires_grad=True)


In [40]:
with torch.no_grad():
    y=x+2
    print(y)

tensor([0.8363, 2.1483, 1.5081])


In [48]:
weights=torch.ones(4, requires_grad=True)
print(f'Weight:{weights}')
for epoch in range(3):
    model_output=(weights*3).sum()
    print(f'Model_output : {model_output}')
    model_output.backward()
    print(f'Weights_grad: {weights.grad}')
    weights.grad.zero_()

Weight:tensor([1., 1., 1., 1.], requires_grad=True)
Model_output : 12.0
Weights_grad: tensor([3., 3., 3., 3.])
Model_output : 12.0
Weights_grad: tensor([3., 3., 3., 3.])
Model_output : 12.0
Weights_grad: tensor([3., 3., 3., 3.])
