# Pytorch has a capability of automatic  gradient calculation !
# In this Notebook We will learn each and every thing about autograd !

#################### Auto Grad ######################################
# Why we require auto grad !
""" 
When we do backpropragation we need to calculate gradient of loss function w.r.t weigth 
If we do gradient calculation with hands it will take time and it wont be dynamic as then we would have to write  
each derivative manually. To resolve this issue pytorch has a capability to calculate derivative of function automatically
which is also known as Auto Grad.  

"""
import torch 
from torch.autograd import grad 
import torch.nn as nn

# A simplified model of a PyTorch tensor is as an object containing the following properties:
1. data — a self-reference (per the above).
2. required_grad — whether or not this tensor is/should be connected to the computational graph.
3. grad — if required_grad is true, this prop will be a sub-tensor that collects the gradients against this tensor accumulated during backwards().
4. grad_fn — This is a reference to the most recent operation which generated this tensor. PyTorch performs automatic differentiation by looking through the grad_fn list.
5. is_leaf — Whether or not this is a leaf node.

# Simple Derivative

In [2]:
# Lets Take an simple Example 
x=torch.tensor(5.0, requires_grad=True)
x

tensor(5., requires_grad=True)

In [3]:
y=x**2
y

tensor(25., grad_fn=<PowBackward0>)

In [4]:
# Lets calculate Gradient by hand 
#  dy/dx = 2*x --- > 2x5 = 10
y.backward()
x.grad

tensor(10.)

# Partial Derivative

In [5]:
# Now lets apply Partial derivative 
x = torch.tensor(5.0,requires_grad=True)
y = torch.tensor(5.0,requires_grad=True)

f = x**2 + y**2

f.backward()
# df/dx = 2*x --- > 2*5 =10
# df/dy = 2*y --- > 2*5 =10

print(f.grad_fn)
print(x.grad)
print(y.grad)

# Here x , y Does not depend on each other they are in addition 
# So x has it's value independent of y and vice versa but 
# What if they are in multiply ?

tensor(10.)
tensor(10.)


In [7]:
x

tensor(5., requires_grad=True)

In [8]:
x = torch.tensor(5.0,requires_grad=True)
y = torch.tensor(5.0,requires_grad=True)

f = x**2 * y**2

f.backward()
# df/dx = 2*x*y^2 --- > 2*5*25 = 250
# df/dy = 2*y*x^2 --- > 2*5*25 = 250

print(f.grad_fn)
print(x.grad)
print(y.grad)

tensor(250.)
tensor(250.)


# Nth derivative

In [16]:
# Lets Do the double derivative
def nth_derivative(f, wrt, n):

    for i in range(n):
        grads = grad(f, wrt, create_graph=True)[0]
        print(f"Grads : {grads}")
        f = grads.sum()
        print(f"Grad Sum : {f}")
        
    return grads

x = torch.tensor(5.0,requires_grad=True)

f = x**2 + x**3
print(nth_derivative(f=f, wrt=x, n=4))

Grads : 85.0
Grad Sum : 85.0
Grads : 32.0
Grad Sum : 32.0
Grads : 6.0
Grad Sum : 6.0
Grads : 0.0
Grad Sum : 0.0
tensor(0.)


In [10]:
print(nth_derivative(f=f, wrt=x, n=1))

tensor(85., grad_fn=<AddBackward0>)


In [11]:
print(nth_derivative(f=f, wrt=x, n=2))

tensor(32., grad_fn=<AddBackward0>)


In [12]:
print(nth_derivative(f=f, wrt=x, n=4))

tensor(0.)


# Derivative of a tensor

In [17]:
# Derivative On A Tensor
# This will give you error as gradient is only constructed for scaler values 
x = torch.tensor([5.0,4.0,3.0],requires_grad=True)
x

tensor([5., 4., 3.], requires_grad=True)

In [18]:
f=x**2
f

tensor([25., 16.,  9.], grad_fn=<PowBackward0>)

In [20]:
f.backward()
x.grad

RuntimeError: grad can be implicitly created only for scalar outputs

In [21]:
# In order to calculate gradient of tensor we need to convert them in scaler 
x = torch.tensor([5.0,4.0,3.0],requires_grad=True)
x

tensor([5., 4., 3.], requires_grad=True)

In [22]:
f=x**2
f

tensor([25., 16.,  9.], grad_fn=<PowBackward0>)

In [23]:
f.sum()

tensor(50., grad_fn=<SumBackward0>)

In [25]:
f.sum().backward()

In [ ]:
x.grad