In [1]:
import torch

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x=torch.randn(3)
x

tensor([ 1.4423,  0.5602, -0.5056])

In [4]:
x=torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [5]:
x=torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [9]:
x=torch.ones(2,2, dtype=torch.float16)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [10]:
x=torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [11]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)


tensor([[0.6376, 0.2753],
        [0.1269, 0.6656]])
tensor([[0.6199, 0.2978],
        [0.8260, 0.0243]])


In [12]:
z=x+y
print(z)

tensor([[1.2575, 0.5731],
        [0.9529, 0.6899]])


In [13]:
z=torch.add(x,y)
z

tensor([[1.2575, 0.5731],
        [0.9529, 0.6899]])

In [14]:
y.add_(x)
print(y)

tensor([[1.2575, 0.5731],
        [0.9529, 0.6899]])
