In [1]:
import torch
import numpy as np

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Tensor initialization
   1. Dtype
   2. Device - cpu or gpu
   3. requires _ grad --> gradient decent , during back prop

 This line repesents that if your system has gpu it will be used else cpu 
 Makes your code work in both condition

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
device

'cpu'

In [4]:
tensor=torch.tensor([[1,2,3],[5,6,7]], 
                   dtype=torch.float,
                   device=device, requires_grad=True)
print(tensor)

tensor([[1., 2., 3.],
        [5., 6., 7.]], requires_grad=True)


In [5]:
print(tensor.dtype)

torch.float32


In [6]:
print(tensor.device)

cpu


In [7]:
print(tensor.shape)

torch.Size([2, 3])


In [8]:
print(tensor.requires_grad)

True


# Other initialization in Tensor

In [10]:
# empty will create space of size with random values 
x=torch.empty(size=(2,3))
print(x)

tensor([[2.6947e-09, 1.0324e-05, 3.3061e+21],
        [6.8997e-07, 4.2115e-11, 7.1450e+31]])


In [12]:
# Zeros
x=torch.zeros(size=(2,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
#ones
x=torch.ones(size=(4,2))
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [15]:
# Random
x=torch.randn(size=(3,7))
print(x)

tensor([[ 9.4348e-01,  4.5572e-01,  1.2830e+00, -6.4295e-02, -3.2388e-01,
          5.3008e-01,  1.2825e-01],
        [-8.1734e-01, -1.3577e+00,  1.5795e+00, -4.6170e-01,  6.7409e-02,
          3.8714e-01, -8.1798e-01],
        [ 1.7716e+00,  4.3377e-01,  2.6834e+00, -2.2035e-03,  4.1423e-02,
         -1.4987e-01, -1.4235e+00]])


In [16]:
# eye identity matrix
x=torch.eye(4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [17]:
# eye identity matrix
x=torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [19]:
# eye identity matrix
x=torch.linspace(start=1, end=10,steps=11)
print(x)

tensor([ 1.0000,  1.9000,  2.8000,  3.7000,  4.6000,  5.5000,  6.4000,  7.3000,
         8.2000,  9.1000, 10.0000])


In [20]:
# empty with normal and uniform 
x = torch.empty(size=(3,3)).normal_(mean=0,std=1)
print(x)

tensor([[-0.2457, -2.6039,  0.9887],
        [ 0.4046, -0.3039, -0.5894],
        [-0.5229,  0.5263,  1.0422]])


In [21]:
x = torch.empty(size=(3,3)).uniform_()
print(x)


tensor([[0.0046, 0.4571, 0.9282],
        [0.6413, 0.9768, 0.4837],
        [0.1036, 0.1844, 0.5124]])


In [22]:
# diagnal matrix 
x = torch.diag(torch.ones(10))
print(x)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


# How to convert tensor to different data types(int,float,double)

In [23]:
x=torch.arange(4)
print(x)

tensor([0, 1, 2, 3])


In [24]:
print(x.bool())

tensor([False,  True,  True,  True])


In [25]:
print(x.int())

tensor([0, 1, 2, 3], dtype=torch.int32)


In [26]:
print(x.float())

tensor([0., 1., 2., 3.])


In [27]:
print(x.long())

tensor([0, 1, 2, 3])


In [28]:
print(x.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [29]:
print(x.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [30]:
print(x.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


# How to convert from numpy to tensor

In [31]:
np_array=np.array([[1,2,3],[4,5,6]])
print(np_array)
tensor=torch.from_numpy(np_array)
print(tensor)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


# Tensor Maths or Arthmatic operations 

In [33]:
x=torch.arange(start=10,end=20, step=4)
print(x)

tensor([10, 14, 18])


In [34]:
y=torch.arange(start=5,end=20,step=4)
print(y)

tensor([ 5,  9, 13, 17])


In [35]:
print('Add :',x+y)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [36]:
y=torch.arange(start=5,end=15,step=4)
print(y)

tensor([ 5,  9, 13])


In [37]:
print('Add :',x+y)

Add : tensor([15, 23, 31])


In [39]:
z1=torch.empty(3)
print(z1)

tensor([3.3543e-24, 4.5911e-41, 0.0000e+00])


In [40]:
torch.add(x,y,out=z1)

tensor([15., 23., 31.])

In [41]:
print('Using empty :', z1)

Using empty : tensor([15., 23., 31.])


In [42]:
print('Direct:', torch.add(x,y))

Direct: tensor([15, 23, 31])


In [43]:
# Subtraction
print('Subtract:', x-y)

Subtract: tensor([5, 5, 5])


In [44]:
# multiplication
print('MUL :', x*y)

MUL : tensor([ 50, 126, 234])


In [45]:
#division
z=x/y
print(z)

tensor([2.0000, 1.5556, 1.3846])


In [46]:
# --> Whenever we see operation having _ that means they are inplace
# Inplace
z=torch.ones(3)
print(z)

tensor([1., 1., 1.])


In [47]:
x

tensor([10, 14, 18])

In [48]:
z.add_(x)

tensor([11., 15., 19.])

In [49]:
# way2 inplace
z +=x

In [50]:
z

tensor([21., 29., 37.])

In [51]:
# power, Exponential
z=x.pow(2)
print(z)

tensor([100, 196, 324])


In [52]:
z

tensor([100, 196, 324])

In [53]:
z=x**2
print(z)

tensor([100, 196, 324])


In [54]:
# Comparison
z=x>0
print(z)

tensor([True, True, True])


# Matrix Multiplication 

In [55]:
x1=torch.rand(size=(3,5))
x2=torch.rand(size=(5,3))
print(x1)

tensor([[0.6926, 0.9868, 0.3971, 0.4488, 0.0666],
        [0.4658, 0.7878, 0.4612, 0.4798, 0.7404],
        [0.3566, 0.8372, 0.2397, 0.4110, 0.5954]])


In [56]:
print(x2)

tensor([[0.5620, 0.7469, 0.5353],
        [0.4062, 0.7903, 0.3590],
        [0.7614, 0.0075, 0.5396],
        [0.5145, 0.7942, 0.5731],
        [0.8907, 0.8138, 0.2284]])


In [57]:
x1@x2

tensor([[1.3827, 1.7108, 1.2117],
        [1.8394, 1.9576, 1.2251],
        [1.4647, 1.7407, 0.9923]])

In [58]:
x1.matmul(x2)

tensor([[1.3827, 1.7108, 1.2117],
        [1.8394, 1.9576, 1.2251],
        [1.4647, 1.7407, 0.9923]])

# Matrix exponential

In [64]:
m1=torch.rand((5,5))
#m1.matrix_exp(m1)

In [65]:
m1

tensor([[0.4800, 0.0222, 0.7870, 0.5627, 0.1582],
        [0.9058, 0.8002, 0.5355, 0.3941, 0.3549],
        [0.5844, 0.3635, 0.2179, 0.5116, 0.9827],
        [0.8300, 0.2613, 0.3675, 0.8447, 0.5469],
        [0.5529, 0.2718, 0.7139, 0.3134, 0.6748]])

In [60]:
m1.matrix_exp()

tensor([[2.3651, 1.6223, 1.2221, 1.7741, 1.1099],
        [1.6292, 2.6772, 2.0198, 1.1039, 1.8609],
        [1.2903, 1.6056, 2.6096, 0.8472, 0.9892],
        [0.6599, 1.0219, 0.9116, 1.4685, 0.5803],
        [1.0193, 1.9898, 1.9488, 0.9182, 2.0800]])

In [66]:
m1.matrix_power(3)

tensor([[3.2833, 1.4128, 2.8089, 2.7789, 2.7628],
        [4.9411, 2.2764, 4.0695, 4.1313, 4.1125],
        [4.3195, 1.9642, 3.5791, 3.6329, 3.7664],
        [4.6177, 2.0120, 3.8076, 3.9677, 3.9536],
        [4.0940, 1.8633, 3.4665, 3.3965, 3.5345]])

# Dot Product 
1. sum of element wise multiplication

In [67]:
x

tensor([10, 14, 18])

In [68]:
y

tensor([ 5,  9, 13])

In [69]:
result=torch.dot(x,y)
print(result)

tensor(410)


# Batch Matrix Multiplication 

In [72]:
batch=5
n=4
m=5
p=4
m1=torch.rand(size=(batch,n,m))
m2=torch.rand(size=(batch,m,p))

print('M1: ', m1)

M1:  tensor([[[8.7587e-01, 8.9026e-01, 4.5607e-01, 8.5685e-01, 3.1394e-01],
         [6.2134e-01, 2.8528e-01, 1.4898e-01, 4.2933e-01, 2.5700e-01],
         [4.7855e-01, 3.2789e-01, 9.7852e-01, 3.2964e-01, 9.3895e-01],
         [1.8523e-01, 3.6332e-02, 4.9265e-01, 4.8556e-01, 5.4476e-01]],

        [[8.2890e-01, 1.0410e-01, 9.5281e-01, 9.7988e-01, 5.2443e-01],
         [9.3822e-01, 3.0279e-01, 9.6716e-01, 4.7548e-01, 7.3291e-01],
         [5.0817e-01, 3.4428e-01, 8.3357e-01, 7.8833e-01, 5.7969e-01],
         [7.3900e-01, 4.2864e-01, 5.2325e-01, 4.2065e-01, 5.5537e-01]],

        [[5.7173e-01, 5.0454e-01, 5.6042e-01, 3.0231e-01, 1.9851e-01],
         [3.2272e-01, 5.7823e-02, 5.2817e-01, 6.7255e-01, 9.5686e-01],
         [9.5883e-01, 7.9568e-01, 5.8060e-01, 6.2959e-03, 8.6803e-01],
         [9.4463e-01, 5.1220e-01, 8.1886e-01, 7.4432e-01, 5.9452e-01]],

        [[7.0750e-01, 1.9616e-01, 2.2088e-01, 7.9471e-04, 1.5242e-01],
         [6.9467e-01, 1.3073e-01, 6.8200e-01, 3.2863e-01, 6.7220e-

In [73]:
print('M2 :', m2)

M2 : tensor([[[0.5435, 0.2757, 0.2216, 0.1705],
         [0.5713, 0.9912, 0.0682, 0.2453],
         [0.5423, 0.1868, 0.0311, 0.4993],
         [0.4309, 0.7937, 0.2834, 0.0345],
         [0.4531, 0.6928, 0.8409, 0.7653]],

        [[0.9300, 0.5838, 0.4325, 0.8891],
         [0.3670, 0.0946, 0.1557, 0.0735],
         [0.8090, 0.2926, 0.0125, 0.3835],
         [0.1647, 0.0890, 0.8446, 0.2668],
         [0.0380, 0.4339, 0.0191, 0.3500]],

        [[0.0629, 0.2106, 0.5597, 0.9877],
         [0.7330, 0.6240, 0.6013, 0.3153],
         [0.1850, 0.8371, 0.6387, 0.5944],
         [0.2015, 0.0860, 0.9887, 0.9765],
         [0.8871, 0.9363, 0.3200, 0.0563]],

        [[0.2451, 0.5681, 0.9460, 0.3776],
         [0.1541, 0.1837, 0.4924, 0.2129],
         [0.2531, 0.1970, 0.3006, 0.2525],
         [0.0474, 0.5597, 0.5656, 0.1196],
         [0.3801, 0.5276, 0.3263, 0.5221]],

        [[0.4502, 0.8388, 0.2669, 0.0816],
         [0.2083, 0.9541, 0.5715, 0.0840],
         [0.0868, 0.1667, 0.8247, 0.8849]

In [74]:
output=torch.bmm(m1,m2)
print(output)

tensor([[[1.7434, 2.1067, 0.7758, 0.8653],
         [0.8829, 1.0007, 0.4995, 0.4618],
         [1.5456, 1.5518, 1.0418, 1.3806],
         [0.8447, 0.9419, 0.6545, 0.7201]],

        [[1.7612, 1.0873, 1.2242, 1.5550],
         [1.8722, 1.2197, 0.8805, 1.6107],
         [1.4251, 0.8948, 0.9607, 1.2100],
         [1.3582, 0.9035, 0.7587, 1.1958]],

        [[0.7465, 1.1162, 1.3438, 1.3633],
         [1.1448, 1.4999, 1.5239, 1.3615],
         [1.5223, 1.9977, 1.6699, 1.5980],
         [1.2638, 1.8247, 2.2859, 2.3415]],

        [[0.3175, 0.5623, 0.8825, 0.4444],
         [0.6341, 1.0916, 1.3318, 0.8526],
         [0.6685, 1.1065, 1.5104, 0.8726],
         [0.6020, 1.0579, 1.1281, 0.8150]],

        [[0.7898, 1.0160, 1.4219, 0.8367],
         [1.3762, 0.9351, 1.2693, 0.5745],
         [0.4910, 0.9791, 1.1588, 0.7070],
         [1.5647, 1.7310, 2.0612, 1.2257]]])


In [75]:
output.size()

torch.Size([5, 4, 4])

# Broadcasting

In [76]:
x1=torch.ones((5,5))
x2=torch.ones((1,5))

In [77]:
x1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [80]:
x2

tensor([[1., 1., 1., 1., 1.]])

In [79]:
x1-x2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# Other usefull Tensor Operations 

In [81]:
x1=torch.ones((5,5))
x1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [82]:
torch.sum(x1)

tensor(25.)

In [83]:
x1=torch.rand((5,5))
x1

tensor([[0.7806, 0.6723, 0.0637, 0.8535, 0.7117],
        [0.0771, 0.0588, 0.3840, 0.5517, 0.3978],
        [0.4015, 0.1248, 0.3441, 0.5113, 0.0873],
        [0.0642, 0.9303, 0.1086, 0.2264, 0.0057],
        [0.4846, 0.0561, 0.2164, 0.2915, 0.9939]])

In [84]:
print(torch.max(x1))

tensor(0.9939)


In [86]:
print(torch.max(x1, dim=1))

torch.return_types.max(
values=tensor([0.8535, 0.5517, 0.5113, 0.9303, 0.9939]),
indices=tensor([3, 3, 3, 1, 4]))


In [87]:
print(torch.max(x1, dim=0))

torch.return_types.max(
values=tensor([0.7806, 0.9303, 0.3840, 0.8535, 0.9939]),
indices=tensor([0, 3, 1, 0, 4]))


In [88]:
x1

tensor([[0.7806, 0.6723, 0.0637, 0.8535, 0.7117],
        [0.0771, 0.0588, 0.3840, 0.5517, 0.3978],
        [0.4015, 0.1248, 0.3441, 0.5113, 0.0873],
        [0.0642, 0.9303, 0.1086, 0.2264, 0.0057],
        [0.4846, 0.0561, 0.2164, 0.2915, 0.9939]])

In [89]:
torch.abs(x1)

tensor([[0.7806, 0.6723, 0.0637, 0.8535, 0.7117],
        [0.0771, 0.0588, 0.3840, 0.5517, 0.3978],
        [0.4015, 0.1248, 0.3441, 0.5113, 0.0873],
        [0.0642, 0.9303, 0.1086, 0.2264, 0.0057],
        [0.4846, 0.0561, 0.2164, 0.2915, 0.9939]])

In [90]:
torch.argmax(x1)

tensor(24)

In [91]:
torch.argmin(x1)

tensor(19)

In [92]:
torch.mean(x1)

tensor(0.3759)

In [93]:
x

tensor([10, 14, 18])

In [94]:
y

tensor([ 5,  9, 13])

In [95]:
torch.eq(x,y)

tensor([False, False, False])

In [97]:
torch.sort(x)# return sorted  value and indices

torch.return_types.sort(
values=tensor([10, 14, 18]),
indices=tensor([0, 1, 2]))

In [98]:

# if values less than zero then it will put that 0
torch.clamp(x, min=5)

tensor([10, 14, 18])

In [99]:
torch.clamp(x, min=16)

tensor([16, 16, 18])

In [100]:
torch.any(x)

tensor(True)

In [101]:
# Indexing in the tensor 

batch = 10
features = 25
x = torch.rand(size=(batch,features))
#print(x)
# rows , cols
# x[start:stop:step,start:stop:step]


In [102]:
x

tensor([[5.4374e-01, 9.5240e-01, 5.9565e-01, 1.7934e-01, 8.4439e-01, 6.6913e-01,
         4.4267e-01, 2.9546e-02, 2.0731e-01, 6.0494e-01, 3.4192e-01, 7.5752e-01,
         6.2964e-01, 7.5387e-02, 5.6603e-01, 2.8902e-01, 1.6801e-01, 7.5207e-01,
         1.7540e-01, 6.8936e-01, 3.2543e-01, 6.4934e-01, 9.0053e-01, 4.2326e-01,
         5.3212e-01],
        [6.5440e-01, 5.4918e-01, 3.3268e-01, 8.0034e-01, 4.0599e-01, 5.6491e-01,
         2.0759e-01, 5.2354e-01, 4.3855e-01, 5.6704e-01, 6.3987e-01, 3.0984e-01,
         8.9874e-01, 8.5809e-01, 3.4588e-01, 2.3361e-01, 4.7014e-01, 3.6297e-01,
         1.2043e-01, 5.5715e-01, 7.8556e-01, 4.3673e-01, 2.4108e-01, 3.5287e-01,
         2.9393e-01],
        [7.2291e-01, 8.7849e-01, 1.8508e-01, 3.2986e-01, 4.2774e-01, 7.0526e-01,
         3.5666e-01, 5.0460e-01, 4.0654e-01, 1.7570e-01, 2.1695e-01, 3.5339e-01,
         5.4346e-01, 1.6826e-01, 2.5466e-01, 2.9181e-01, 2.3761e-01, 5.3852e-01,
         5.1881e-01, 1.4133e-01, 4.1354e-01, 4.0747e-01, 3.3011e-

In [103]:
print(x[0,10:])

tensor([0.3419, 0.7575, 0.6296, 0.0754, 0.5660, 0.2890, 0.1680, 0.7521, 0.1754,
        0.6894, 0.3254, 0.6493, 0.9005, 0.4233, 0.5321])


In [104]:
print(x[:,0])
print(x[0:2,0:2])
x[0,0] = 1000

tensor([0.5437, 0.6544, 0.7229, 0.9585, 0.1345, 0.5425, 0.3508, 0.0273, 0.1381,
        0.7382])
tensor([[0.5437, 0.9524],
        [0.6544, 0.5492]])


In [105]:
x[0,0] = 1000

In [106]:
x

tensor([[1.0000e+03, 9.5240e-01, 5.9565e-01, 1.7934e-01, 8.4439e-01, 6.6913e-01,
         4.4267e-01, 2.9546e-02, 2.0731e-01, 6.0494e-01, 3.4192e-01, 7.5752e-01,
         6.2964e-01, 7.5387e-02, 5.6603e-01, 2.8902e-01, 1.6801e-01, 7.5207e-01,
         1.7540e-01, 6.8936e-01, 3.2543e-01, 6.4934e-01, 9.0053e-01, 4.2326e-01,
         5.3212e-01],
        [6.5440e-01, 5.4918e-01, 3.3268e-01, 8.0034e-01, 4.0599e-01, 5.6491e-01,
         2.0759e-01, 5.2354e-01, 4.3855e-01, 5.6704e-01, 6.3987e-01, 3.0984e-01,
         8.9874e-01, 8.5809e-01, 3.4588e-01, 2.3361e-01, 4.7014e-01, 3.6297e-01,
         1.2043e-01, 5.5715e-01, 7.8556e-01, 4.3673e-01, 2.4108e-01, 3.5287e-01,
         2.9393e-01],
        [7.2291e-01, 8.7849e-01, 1.8508e-01, 3.2986e-01, 4.2774e-01, 7.0526e-01,
         3.5666e-01, 5.0460e-01, 4.0654e-01, 1.7570e-01, 2.1695e-01, 3.5339e-01,
         5.4346e-01, 1.6826e-01, 2.5466e-01, 2.9181e-01, 2.3761e-01, 5.3852e-01,
         5.1881e-01, 1.4133e-01, 4.1354e-01, 4.0747e-01, 3.3011e-

In [107]:
print(x[x.remainder(2)==0])

tensor([1000.])


In [108]:
print(x.unique()[:5])
print(torch.where(x<5 ,0 , 1 )[:1,:1]) # where x, y
print(x.ndimension()) # gives dim
print(x.numel())  # count number of elements in x

tensor([8.4937e-05, 3.1146e-03, 7.7726e-03, 1.2338e-02, 1.5814e-02])
tensor([[1]])
2
250


# Reshaping of Tensor

In [109]:
x=torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
print(x.view(3,3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [111]:
print(x.view(2,3))

RuntimeError: shape '[2, 3]' is invalid for input of size 9

In [112]:
print(x.reshape(3,3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [113]:
print(x.reshape(3,4))

RuntimeError: shape '[3, 4]' is invalid for input of size 9

In [114]:
print(x.reshape(3,3).t())

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [116]:
# concatination
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(x1)
print(x2)
print(torch.cat((x1,x2),dim=1)) # dim 0  add rows , dim 1 add cols 


tensor([[0.6575, 0.7540, 0.9513, 0.5324, 0.0151],
        [0.9102, 0.5730, 0.0880, 0.9706, 0.3857]])
tensor([[0.6673, 0.4930, 0.7238, 0.5104, 0.3345],
        [0.8509, 0.9247, 0.7715, 0.8331, 0.6273]])
tensor([[0.6575, 0.7540, 0.9513, 0.5324, 0.0151, 0.6673, 0.4930, 0.7238, 0.5104,
         0.3345],
        [0.9102, 0.5730, 0.0880, 0.9706, 0.3857, 0.8509, 0.9247, 0.7715, 0.8331,
         0.6273]])


In [117]:

# Flatten tensor
print(x1.shape)

torch.Size([2, 5])


In [118]:
x1.view(-1).shape

torch.Size([10])

In [121]:
# batch Flatten
batch = 16
torch.rand((batch,2,5))
#torch.rand((batch,2,5)).view((batch,-1))



tensor([[[0.9619, 0.6235, 0.6701, 0.2437, 0.8583],
         [0.5519, 0.5553, 0.6195, 0.6012, 0.2177]],

        [[0.4077, 0.9550, 0.0617, 0.7842, 0.5291],
         [0.8705, 0.0331, 0.5257, 0.9123, 0.6161]],

        [[0.0369, 0.7165, 0.9513, 0.5589, 0.2209],
         [0.4556, 0.7869, 0.9084, 0.3874, 0.3677]],

        [[0.5807, 0.1357, 0.4599, 0.1528, 0.0678],
         [0.2486, 0.3409, 0.3388, 0.2562, 0.3589]],

        [[0.1976, 0.7038, 0.9123, 0.4430, 0.0162],
         [0.6794, 0.9484, 0.0364, 0.8935, 0.0348]],

        [[0.1524, 0.1166, 0.0622, 0.1812, 0.8789],
         [0.2395, 0.3729, 0.6721, 0.2791, 0.8015]],

        [[0.6124, 0.8413, 0.6716, 0.8020, 0.4056],
         [0.6044, 0.1572, 0.7252, 0.5515, 0.4423]],

        [[0.8415, 0.7839, 0.1748, 0.0019, 0.8651],
         [0.0917, 0.5126, 0.5483, 0.6293, 0.0369]],

        [[0.4243, 0.8525, 0.8946, 0.6858, 0.4930],
         [0.0038, 0.7037, 0.2071, 0.9790, 0.4854]],

        [[0.7650, 0.9550, 0.7371, 0.1750, 0.9760],
         [0.1

In [122]:
torch.rand((batch,2,5)).view((batch,-1))

tensor([[7.3786e-01, 1.2055e-01, 5.0100e-01, 3.6275e-04, 2.6172e-01, 8.2070e-01,
         3.1268e-02, 9.3699e-01, 5.0705e-01, 3.4455e-01],
        [1.4931e-01, 7.9193e-01, 4.3256e-01, 9.2831e-02, 7.6608e-01, 3.9574e-01,
         8.8301e-01, 3.7670e-01, 8.8690e-01, 9.1231e-01],
        [7.5499e-01, 1.0451e-02, 9.9383e-01, 2.5265e-01, 2.0979e-01, 1.3917e-02,
         7.2844e-01, 7.9048e-01, 5.5016e-01, 4.3900e-01],
        [9.3710e-01, 7.8900e-01, 1.4418e-01, 9.3906e-01, 6.3726e-01, 5.0218e-01,
         7.3002e-02, 8.9518e-01, 9.7175e-01, 5.6688e-02],
        [6.4922e-01, 7.7185e-02, 7.1840e-03, 5.1550e-01, 3.2623e-01, 3.9496e-01,
         5.4715e-01, 6.0403e-01, 8.3112e-01, 8.0405e-01],
        [9.6380e-01, 5.8242e-01, 3.2450e-01, 2.3425e-01, 1.7426e-01, 6.1250e-01,
         5.6868e-01, 3.6447e-01, 5.9561e-01, 3.1857e-01],
        [2.4766e-01, 8.7184e-01, 5.6102e-02, 6.3962e-01, 7.0350e-02, 4.0299e-01,
         4.0724e-01, 3.7559e-01, 7.7357e-01, 1.7266e-01],
        [6.6067e-01, 2.9919

In [123]:
x1

tensor([[0.6575, 0.7540, 0.9513, 0.5324, 0.0151],
        [0.9102, 0.5730, 0.0880, 0.9706, 0.3857]])

In [124]:
# Reshape manually 
x1.permute(1,0)  # index position of dimen

tensor([[0.6575, 0.9102],
        [0.7540, 0.5730],
        [0.9513, 0.0880],
        [0.5324, 0.9706],
        [0.0151, 0.3857]])

In [125]:
x1.permute(0,1)

tensor([[0.6575, 0.7540, 0.9513, 0.5324, 0.0151],
        [0.9102, 0.5730, 0.0880, 0.9706, 0.3857]])

In [126]:
x = torch.randn(2, 3, 5)
x

tensor([[[ 1.1862, -0.6017, -0.5638,  0.2152,  0.8167],
         [-0.4987,  1.3854, -1.5437,  0.1715,  0.3572],
         [ 1.0007,  0.0071,  0.4846,  0.9178, -0.3341]],

        [[-1.2471,  0.9155, -0.2159, -0.3839, -0.5085],
         [ 0.7519, -0.7713, -1.8623,  1.2070,  0.7447],
         [ 0.1038,  1.0026,  1.2683, -0.9088, -0.1489]]])

In [127]:
x.size()

torch.Size([2, 3, 5])

In [128]:
torch.permute(x,(2,0,1))

tensor([[[ 1.1862, -0.4987,  1.0007],
         [-1.2471,  0.7519,  0.1038]],

        [[-0.6017,  1.3854,  0.0071],
         [ 0.9155, -0.7713,  1.0026]],

        [[-0.5638, -1.5437,  0.4846],
         [-0.2159, -1.8623,  1.2683]],

        [[ 0.2152,  0.1715,  0.9178],
         [-0.3839,  1.2070, -0.9088]],

        [[ 0.8167,  0.3572, -0.3341],
         [-0.5085,  0.7447, -0.1489]]])

In [129]:
torch.permute(x,(2,0,1)).size()

torch.Size([5, 2, 3])