In [1]:
import torch
import numpy as np

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Tensor initialization
   1. Dtype
   2. Device - cpu or gpu
   3. requires _ grad --> gradient decent , during back prop

 This line repesents that if your system has gpu it will be used else cpu 
 Makes your code work in both condition

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
device

'cpu'

In [4]:
tensor=torch.tensor([[1,2,3],[5,6,7]], 
                   dtype=torch.float,
                   device=device, requires_grad=True)
print(tensor)

tensor([[1., 2., 3.],
        [5., 6., 7.]], requires_grad=True)


In [5]:
print(tensor.dtype)

torch.float32


In [6]:
print(tensor.device)

cpu


In [7]:
print(tensor.shape)

torch.Size([2, 3])


In [8]:
print(tensor.requires_grad)

True


# Other initialization in Tensor

In [10]:
# empty will create space of size with random values 
x=torch.empty(size=(2,3))
print(x)

tensor([[2.6947e-09, 1.0324e-05, 3.3061e+21],
        [6.8997e-07, 4.2115e-11, 7.1450e+31]])


In [12]:
# Zeros
x=torch.zeros(size=(2,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
#ones
x=torch.ones(size=(4,2))
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [15]:
# Random
x=torch.randn(size=(3,7))
print(x)

tensor([[ 9.4348e-01,  4.5572e-01,  1.2830e+00, -6.4295e-02, -3.2388e-01,
          5.3008e-01,  1.2825e-01],
        [-8.1734e-01, -1.3577e+00,  1.5795e+00, -4.6170e-01,  6.7409e-02,
          3.8714e-01, -8.1798e-01],
        [ 1.7716e+00,  4.3377e-01,  2.6834e+00, -2.2035e-03,  4.1423e-02,
         -1.4987e-01, -1.4235e+00]])


In [16]:
# eye identity matrix
x=torch.eye(4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [17]:
# eye identity matrix
x=torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [19]:
# eye identity matrix
x=torch.linspace(start=1, end=10,steps=11)
print(x)

tensor([ 1.0000,  1.9000,  2.8000,  3.7000,  4.6000,  5.5000,  6.4000,  7.3000,
         8.2000,  9.1000, 10.0000])


In [20]:
# empty with normal and uniform 
x = torch.empty(size=(3,3)).normal_(mean=0,std=1)
print(x)

tensor([[-0.2457, -2.6039,  0.9887],
        [ 0.4046, -0.3039, -0.5894],
        [-0.5229,  0.5263,  1.0422]])


In [21]:
x = torch.empty(size=(3,3)).uniform_()
print(x)


tensor([[0.0046, 0.4571, 0.9282],
        [0.6413, 0.9768, 0.4837],
        [0.1036, 0.1844, 0.5124]])


In [22]:
# diagnal matrix 
x = torch.diag(torch.ones(10))
print(x)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


# How to convert tensor to different data types(int,float,double)

In [23]:
x=torch.arange(4)
print(x)

tensor([0, 1, 2, 3])


In [24]:
print(x.bool())

tensor([False,  True,  True,  True])


In [25]:
print(x.int())

tensor([0, 1, 2, 3], dtype=torch.int32)


In [26]:
print(x.float())

tensor([0., 1., 2., 3.])


In [27]:
print(x.long())

tensor([0, 1, 2, 3])


In [28]:
print(x.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [29]:
print(x.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [30]:
print(x.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


# How to convert from numpy to tensor

In [31]:
np_array=np.array([[1,2,3],[4,5,6]])
print(np_array)
tensor=torch.from_numpy(np_array)
print(tensor)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


# Tensor Maths or Arthmatic operations 

In [33]:
x=torch.arange(start=10,end=20, step=4)
print(x)

tensor([10, 14, 18])


In [34]:
y=torch.arange(start=5,end=20,step=4)
print(y)

tensor([ 5,  9, 13, 17])


In [35]:
print('Add :',x+y)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [36]:
y=torch.arange(start=5,end=15,step=4)
print(y)

tensor([ 5,  9, 13])


In [37]:
print('Add :',x+y)

Add : tensor([15, 23, 31])


In [39]:
z1=torch.empty(3)
print(z1)

tensor([3.3543e-24, 4.5911e-41, 0.0000e+00])


In [40]:
torch.add(x,y,out=z1)

tensor([15., 23., 31.])

In [41]:
print('Using empty :', z1)

Using empty : tensor([15., 23., 31.])


In [42]:
print('Direct:', torch.add(x,y))

Direct: tensor([15, 23, 31])


In [43]:
# Subtraction
print('Subtract:', x-y)

Subtract: tensor([5, 5, 5])


In [44]:
# multiplication
print('MUL :', x*y)

MUL : tensor([ 50, 126, 234])


In [45]:
#division
z=x/y
print(z)

tensor([2.0000, 1.5556, 1.3846])


In [46]:
# --> Whenever we see operation having _ that means they are inplace
# Inplace
z=torch.ones(3)
print(z)

tensor([1., 1., 1.])


In [47]:
x

tensor([10, 14, 18])

In [48]:
z.add_(x)

tensor([11., 15., 19.])

In [49]:
# way2 inplace
z +=x

In [50]:
z

tensor([21., 29., 37.])

In [51]:
# power, Exponential
z=x.pow(2)
print(z)

tensor([100, 196, 324])


In [52]:
z

tensor([100, 196, 324])

In [53]:
z=x**2
print(z)

tensor([100, 196, 324])


In [54]:
# Comparison
z=x>0
print(z)

tensor([True, True, True])


# Matrix Multiplication 

In [55]:
x1=torch.rand(size=(3,5))
x2=torch.rand(size=(5,3))
print(x1)

tensor([[0.6926, 0.9868, 0.3971, 0.4488, 0.0666],
        [0.4658, 0.7878, 0.4612, 0.4798, 0.7404],
        [0.3566, 0.8372, 0.2397, 0.4110, 0.5954]])


In [56]:
print(x2)

tensor([[0.5620, 0.7469, 0.5353],
        [0.4062, 0.7903, 0.3590],
        [0.7614, 0.0075, 0.5396],
        [0.5145, 0.7942, 0.5731],
        [0.8907, 0.8138, 0.2284]])


In [57]:
x1@x2

tensor([[1.3827, 1.7108, 1.2117],
        [1.8394, 1.9576, 1.2251],
        [1.4647, 1.7407, 0.9923]])

In [58]:
x1.matmul(x2)

tensor([[1.3827, 1.7108, 1.2117],
        [1.8394, 1.9576, 1.2251],
        [1.4647, 1.7407, 0.9923]])

# Matrix exponential

In [64]:
m1=torch.rand((5,5))
#m1.matrix_exp(m1)

In [65]:
m1

tensor([[0.4800, 0.0222, 0.7870, 0.5627, 0.1582],
        [0.9058, 0.8002, 0.5355, 0.3941, 0.3549],
        [0.5844, 0.3635, 0.2179, 0.5116, 0.9827],
        [0.8300, 0.2613, 0.3675, 0.8447, 0.5469],
        [0.5529, 0.2718, 0.7139, 0.3134, 0.6748]])

In [60]:
m1.matrix_exp()

tensor([[2.3651, 1.6223, 1.2221, 1.7741, 1.1099],
        [1.6292, 2.6772, 2.0198, 1.1039, 1.8609],
        [1.2903, 1.6056, 2.6096, 0.8472, 0.9892],
        [0.6599, 1.0219, 0.9116, 1.4685, 0.5803],
        [1.0193, 1.9898, 1.9488, 0.9182, 2.0800]])

In [ ]:
m1.matrix_power(3)