In [1]:
import torch
import numpy as np

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Tensor initialization
   1. Dtype
   2. Device - cpu or gpu
   3. requires _ grad --> gradient decent , during back prop

 This line repesents that if your system has gpu it will be used else cpu 
 Makes your code work in both condition

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
device

'cpu'

In [4]:
tensor=torch.tensor([[1,2,3],[5,6,7]], 
                   dtype=torch.float,
                   device=device, requires_grad=True)
print(tensor)

tensor([[1., 2., 3.],
        [5., 6., 7.]], requires_grad=True)


In [5]:
print(tensor.dtype)

torch.float32


In [6]:
print(tensor.device)

cpu


In [7]:
print(tensor.shape)

torch.Size([2, 3])


In [8]:
print(tensor.requires_grad)

True


# Other initialization in Tensor

In [10]:
# empty will create space of size with random values 
x=torch.empty(size=(2,3))
print(x)

tensor([[2.6947e-09, 1.0324e-05, 3.3061e+21],
        [6.8997e-07, 4.2115e-11, 7.1450e+31]])


In [12]:
# Zeros
x=torch.zeros(size=(2,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
#ones
x=torch.ones(size=(4,2))
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [15]:
# Random
x=torch.randn(size=(3,7))
print(x)

tensor([[ 9.4348e-01,  4.5572e-01,  1.2830e+00, -6.4295e-02, -3.2388e-01,
          5.3008e-01,  1.2825e-01],
        [-8.1734e-01, -1.3577e+00,  1.5795e+00, -4.6170e-01,  6.7409e-02,
          3.8714e-01, -8.1798e-01],
        [ 1.7716e+00,  4.3377e-01,  2.6834e+00, -2.2035e-03,  4.1423e-02,
         -1.4987e-01, -1.4235e+00]])


In [16]:
# eye identity matrix
x=torch.eye(4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [17]:
# eye identity matrix
x=torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [19]:
# eye identity matrix
x=torch.linspace(start=1, end=10,steps=11)
print(x)

tensor([ 1.0000,  1.9000,  2.8000,  3.7000,  4.6000,  5.5000,  6.4000,  7.3000,
         8.2000,  9.1000, 10.0000])


In [20]:
# empty with normal and uniform 
x = torch.empty(size=(3,3)).normal_(mean=0,std=1)
print(x)

tensor([[-0.2457, -2.6039,  0.9887],
        [ 0.4046, -0.3039, -0.5894],
        [-0.5229,  0.5263,  1.0422]])


In [21]:
x = torch.empty(size=(3,3)).uniform_()
print(x)


tensor([[0.0046, 0.4571, 0.9282],
        [0.6413, 0.9768, 0.4837],
        [0.1036, 0.1844, 0.5124]])


In [22]:
# diagnal matrix 
x = torch.diag(torch.ones(10))
print(x)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


# How to convert tensor to different data types(int,float,double)

In [23]:
x=torch.arange(4)
print(x)

tensor([0, 1, 2, 3])


In [24]:
print(x.bool())

tensor([False,  True,  True,  True])


In [25]:
print(x.int())

tensor([0, 1, 2, 3], dtype=torch.int32)


In [26]:
print(x.float())

tensor([0., 1., 2., 3.])


In [27]:
print(x.long())

tensor([0, 1, 2, 3])


In [28]:
print(x.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [29]:
print(x.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [30]:
print(x.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


# How to convert from numpy to tensor

In [31]:
np_array=np.array([[1,2,3],[4,5,6]])
print(np_array)
tensor=torch.from_numpy(np_array)
print(tensor)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
