In [1]:
import torch
import numpy as np

D:\AIOPS\mlops-mlflow-pythorch-multistep-workflow\env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
device="cuda" if torch.cuda.is_available() else 'cpu'

In [3]:
device

'cpu'

In [4]:
tensor=torch.tensor([[1,2,3],[1,2,3]], dtype=torch.float, device=device, requires_grad=True)

In [5]:
print(tensor)

tensor([[1., 2., 3.],
        [1., 2., 3.]], requires_grad=True)


In [6]:
tensor.dtype

torch.float32

In [7]:
tensor.shape

torch.Size([2, 3])

In [8]:
tensor.requires_grad

True

In [21]:
tensor1=torch.tensor([[[1,2,3]],[[5,6,7]]], dtype=torch.float, device=device, requires_grad=True)

In [22]:
tensor1

tensor([[[1., 2., 3.]],

        [[5., 6., 7.]]], requires_grad=True)

In [23]:
print(tensor1.dtype)

torch.float32


In [24]:
tensor1.shape

torch.Size([2, 1, 3])

In [25]:
print(tensor1)

tensor([[[1., 2., 3.]],

        [[5., 6., 7.]]], requires_grad=True)


In [28]:
x=torch.empty(size=((2,2)))
x

tensor([[0., 0.],
        [0., 0.]])

In [29]:
x.shape

torch.Size([2, 2])

In [31]:
x=torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [32]:
x=torch.rand(size=(3,3))
x

tensor([[0.5419, 0.5929, 0.8138],
        [0.3890, 0.5743, 0.2005],
        [0.5438, 0.6210, 0.7753]])

In [33]:
x=torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

In [37]:
x=torch.linspace(start=1, end=10, steps=10)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])